# FOOTBALL DATA ANALYSIS  #

#            SPRINT 1

# DATA MERGING,DATA PREPROCESSING,DATA CLEANING ETC. SAVE THE CLEANED DATA FILE AND USE IT FOR ALL FURTHER SPRINTS OF THIS PROJECT

In [1]:
import numpy as np
import pandas as pd

In [2]:
players_file=pd.read_excel(r"C:\Users\marur\Downloads\players.xlsx")
players_file

,player_id,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,194.0,2000000.0,15000000.0,2024-06-30,ROGON
1,223047,Emerson Hyndman,2018,903,emerson-hyndman,United States,1996-04-09,Central Midfield,Midfield,right,170.0,800000.0,1800000.0,NaT,OmniSports
2,307781,Lynden Gooch,2016,289,lynden-gooch,United States,1995-12-24,Right Winger,Attack,right,173.0,1000000.0,1000000.0,2024-06-30,Unique Sports Group
3,370846,Timothy Weah,2023,506,timothy-weah,United States,2000-02-22,Right Midfield,Midfield,right,183.0,14000000.0,15000000.0,2028-06-30,BS Group - BS Law
4,484756,Djordje Mihailovic,2023,1090,djordje-mihailovic,United States,1998-11-10,Attacking Midfield,Midfield,NaN,178.0,5000000.0,6000000.0,2026-06-30,YMU Management Ltd.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,273570,Desevio Payne,2020,1283,desevio-payne,United States,1995-11-30,Right-Back,Defender,right,182.0,NaN,400000.0,NaT,NaN
148,111783,Alejandro Bedoya,2015,995,alejandro-bedoya,United States,1987-04-29,Central Midfield,Midfield,right,182.0,300000.0,2500000.0,2023-12-31,YMU Group
149,160670,Joe Gyau,2014,16,joe-gyau,United States,1992-09-16,Left Winger,Attack,both,175.0,400000.0,600000.0,2023-12-31,BR Group Management
150,3476,Brad Friedel,2014,148,brad-friedel,United States,1971-05-18,Goalkeeper,Goalkeeper,NaN,NaN,NaN,4000000.0,NaT,NaN
151,504215,Giovanni Reyna,2023,16,giovanni-reyna,England,2002-11-13,Attacking Midfield,Midfield,right,185.0,25000000.0,42000000.0,2025-06-30,Wasserman

In [3]:
games_file=pd.read_excel(r"C:\Users\marur\Downloads\games.xlsx")
games_file

,game_id,competition_id,season,round,date,home_club_goals,away_club_goals,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,2222734,RU1,2012,19. Matchday,2012-12-07,2,3,11.0,10.0,Miodrag Bozovic,Slavoljub Muslin,Olimp-2,5700.0,Sergey Kuznetsov,NaN,NaN,FK Rostov,FK Krasnodar,02:03:00,domestic_league
1,2224572,DK1,2012,3. Matchday,2012-07-28,1,2,12.0,1.0,Jess Thorup,Lars Sondergaard,Blue Water Arena,5345.0,Michael Svendsen,NaN,NaN,Esbjerg fB,Sonderjyske Fc,01:02:00,domestic_league
2,2224628,DK1,2012,22. Matchday,2013-03-08,2,0,3.0,10.0,Colin Todd,Lars Sondergaard,Cepheus Park Randers,3481.0,Jakob Kehlet,NaN,NaN,Randers Fodbold Club,Sonderjyske Fc,02:00:00,domestic_league
3,2224655,DK1,2012,22. Matchday,2013-03-10,0,3,6.0,12.0,Peter Rensen,Auri Skarbalius,Ceres Park,7967.0,Kenn Hansen,NaN,NaN,Aarhus Gymnastik Forening,BRA NDBYERNES,00:03:00,domestic_league
4,2224729,DK1,2012,1. Matchday,2012-07-15,0,1,9.0,5.0,Auri Skarbalius,Troels Bech,Brondby Stadium,10806.0,Lars Christoffersen,NaN,NaN,Brondby IF,Odense Boldklub,00:01:00,domestic_league
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3263,3296153,NLP,2019,Round of 16,2020-01-22,7,0,NaN,NaN,Erik ten Hag,Eric Meijers,Johan Cruijff ArenA,52017.0,Richard Martens,NaN,NaN,AFC Ajax Amsterdam,NaN,07:00:00,domestic_cup
3264,2875216,DK1,2017,19. Matchday,2017-12-10,3,2,3.0,4.0,Kasper Hjulmand,Thomas Thomasberg,Right to Dream Park,2843.0,Michael Tykgaard,NaN,NaN,Football Club Nords,Hobro IK,03:02:00,domestic_league
3265,3099247,BE1,2018,11. Matchday,2018-10-20,3,1,9.0,7.0,Glen De Boeck,Marc Brys,Guldensporenstadion,6143.0,Wesley Alen,NaN,NaN,Koninklijke Voetbalclub Kortrijk,Koninklijke Sint-Truidense Voetbalvereniging,03:01:00,domestic_league
3266,2872273,GB1,2017,16. Matchday,2017-12-09,5,1,6.0,15.0,Mauricio Pochettino,Mark Hughes,Wembley Stadium,62202.0,Roger East,NaN,NaN,Tottenham Hotspur Football Club,Stoke City,05:01:00,domestic_league
3267,2517322,FAC,2014,Third Round,2015-01-04,3,1,NaN,NaN,Mark Hughes,Kevin Wilkin,bet365 Stadium,19423.0,Simon Hooper,NaN,NaN,Stoke City,NaN,03:01:00,domestic_cup

In [4]:
game_lineup_file=pd.read_excel(r"C:\Users\marur\Downloads\game_lineups.xlsx")
game_lineup_file

,game_lineups_id,game_id,type,number,player_id,player_name,team_captain,position
0,f2570d1504fc02f4b6c7608e8dcf89a3,4087925,substitutes,34,242284,Ethan Horvath,0,Goalkeeper
1,f5f0da93ea8e1d8bdd799658e7c8f7cb,4087928,starting_lineup,13,145466,Tim Ream,0,Centre-Back
2,31a4d12ec23d604779d909d26c1b5410,4087929,substitutes,26,578539,Chris Richards,0,Centre-Back
3,776dcbef98651450db76723cb7e3b4df,4087935,substitutes,26,578539,Chris Richards,0,Centre-Back
4,6a35ef7495303f29e7f85dbd54547fb1,4087936,starting_lineup,13,145466,Tim Ream,1,Centre-Back
...,...,...,...,...,...,...,...,...
214,ec3d266094f99ca0a8847de827e37105,4194152,starting_lineup,7,504215,Giovanni Reyna,0,Right Winger
215,667840cda9bdf3b0344b8e99b306cf38,4194152,starting_lineup,23,124732,John Anthony Brooks,0,Centre-Back
216,1c5d2f60ee777760f8a757aa10c42bb1,4194154,starting_lineup,13,103064,Terrence Boyd,0,Centre-Forward
217,99032084fd00ffbfee52c541a9f960ab,4204000,substitutes,14,315762,Luca de la Torre,0,Central Midfield
218,5c9eaf6ebb621d43a0d6fd6a9e607ef9,4220942,substitutes,13,145466,Tim Ream,0,Centre-Back

In [5]:
game_event_file=pd.read_excel(r"C:\Users\marur\Downloads\game_events.xlsx")
game_event_file

,game_event_id,date,game_id,minute,type,player_id,description,player_in_id,player_assist_id
0,c6a3c088ed8a38d4ce074dd73b20d3da,2012-08-19,2221641,62,Substitutions,1335,", Not reported",45668.0,NaN
1,02d605a5c2dc4f9a6721daa583fa5405,2012-08-26,2222536,54,Cards,1321,"1. Yellow card , Foul",NaN,NaN
2,b56c2e2e087cddb3cfe9e3d340975df9,2012-11-18,2222707,79,Substitutions,104203,", Tactical",25740.0,NaN
3,4a15d1fff4f476f48bb60092c61641d5,2012-11-23,2222721,72,Substitutions,104203,", Tactical",15583.0,NaN
4,daa97877f7edf2fda885b411d7197921,2013-05-17,2222782,63,Goals,104203,", Right-footed shot, 1. Goal of the Season Ass...",NaN,15077.0
...,...,...,...,...,...,...,...,...,...
1844,4acebccbc824e45d51045d8c5e164341,2023-10-31,4194147,3,Goals,355369,", Left-footed shot, 1. Tournament Goal Assist:...",NaN,284010.0
1845,159ad5633cf9d7c3a97b593efb6c3269,2023-10-31,4194147,9,Goals,355369,", Right-footed shot, 2. Tournament Goal Assist...",NaN,629588.0
1846,daa31f19aab26eec375884aef73c73b3,2023-10-31,4194147,65,Substitutions,355369,", Tactical",544148.0,NaN
1847,869a13060604e769290dafe0b1f14483,2023-11-01,4194152,70,Substitutions,504215,", Tactical",406640.0,NaN
1848,6b7ed06f13c1f67f0d7359c310f20ba0,2023-10-31,4194154,76,Substitutions,103064,", Tactical",378874.0,NaN

In [6]:
app_file=pd.read_excel(r"C:\Users\marur\Downloads\appearances.xlsx")
app_file

,appearance_id,game_id,player_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2224728_119169,2224728,119169,2012-07-13,Aron Johannsson,DK1,0,0,0,0,90
1,2224732_161244,2224732,161244,2012-07-14,Conor O'Brien,DK1,0,0,1,0,90
2,2224729_39467,2224729,39467,2012-07-15,Clarence Goodson,DK1,0,0,0,0,90
3,2232104_119169,2232104,119169,2012-07-19,Aron Johannsson,ELQ,0,0,0,0,74
4,2219794_39475,2219794,39475,2012-07-22,Sacha Kljestan,BESC,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...
3563,3415291_537467,3415291,537467,2020-09-26,Joseph Efford,BE1,0,0,1,0,77
3564,3415296_367423,3415296,367423,2020-09-26,Chris Durkin,BE1,1,0,0,0,84
3565,3431983_478940,3431983,478940,2020-09-26,Reggie Cannon,PO1,0,0,0,0,90
3566,3450575_361104,3450575,361104,2020-09-26,Sergino Dest,NL1,0,0,0,0,6
3567,3412904_124732,3412904,124732,2020-09-27,John Anthony Brooks,L1,1,0,0,0,90

In [8]:
games_file.columns

Index(['game_id', 'competition_id', 'season', 'round', 'date',
       'home_club_goals', 'away_club_goals', 'home_club_position',
       'away_club_position', 'home_club_manager_name',
       'away_club_manager_name', 'stadium', 'attendance', 'referee',
       'home_club_formation', 'away_club_formation', 'home_club_name',
       'away_club_name', 'aggregate', 'competition_type'],
      dtype='object')

In [9]:
game_lineup_file.columns

Index(['game_lineups_id', 'game_id', 'type', 'number', 'player_id',
       'player_name', 'team_captain', 'position'],
      dtype='object')

In [10]:
game_event_file.columns

Index(['game_event_id', 'date', 'game_id', 'minute', 'type', 'player_id',
       'description', 'player_in_id', 'player_assist_id'],
      dtype='object')

In [11]:
players_file.columns

Index(['player_id', 'name', 'last_season', 'current_club_id', 'player_code',
       'country_of_birth', 'date_of_birth', 'sub_position', 'position', 'foot',
       'height_in_cm', 'market_value_in_eur', 'highest_market_value_in_eur',
       'contract_expiration_date', 'agent_name'],
      dtype='object')

In [12]:
app_file.columns

Index(['appearance_id', 'game_id', 'player_id', 'date', 'player_name',
       'competition_id', 'yellow_cards', 'red_cards', 'goals', 'assists',
       'minutes_played'],
      dtype='object')

#  THE GAMES_FILE ,GAME_EVENT_FILE,GAME_LINEUP_FILE,PLAYERS_FILE,APPERANCE_FILE ARE MERGING INTO SINGLE DATA FILE

In [13]:
df=app_file.merge(game_event_file,on=['game_id','player_id'],how='outer')
df1=df.merge(game_lineup_file,on=['game_id','player_id'],how='outer')
df2=df1.merge(games_file,on='game_id',how='outer')
df3=pd.merge(df2,players_file,on='player_id',how='outer')
df3

,appearance_id,game_id,player_id,date_x,player_name_x,competition_id_x,yellow_cards,red_cards,goals,assists,...,country_of_birth,date_of_birth,sub_position,position_y,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,2222536_1321,2222536.0,1321,2012-08-26,Jermaine Jones,L1,1.0,0.0,0.0,1.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,NaN,8000000.0,NaT,NaN
1,2231391_1321,2231391.0,1321,2012-09-01,Jermaine Jones,L1,0.0,0.0,1.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,NaN,8000000.0,NaT,NaN
2,2231391_1321,2231391.0,1321,2012-09-01,Jermaine Jones,L1,0.0,0.0,1.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,NaN,8000000.0,NaT,NaN
3,2231397_1321,2231397.0,1321,2012-09-28,Jermaine Jones,L1,1.0,0.0,0.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,NaN,8000000.0,NaT,NaN
4,2231397_1321,2231397.0,1321,2012-09-28,Jermaine Jones,L1,1.0,0.0,0.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,NaN,8000000.0,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4649,NaN,NaN,795738,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,United States,2003-08-26,Attacking Midfield,Midfield,right,175.0,4500000.0,4500000.0,2027-06-30,Wasserman
4650,NaN,NaN,796429,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,United States,2003-11-18,Right-Back,Defender,right,185.0,1500000.0,3000000.0,2025-12-31,CAA Stellar
4651,NaN,NaN,860812,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,United States,2002-04-22,Left Winger,Attack,right,182.0,350000.0,350000.0,2026-06-30,FGM
4652,NaN,NaN,971613,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,United States,2000-06-21,Defensive Midfield,Midfield,right,193.0,150000.0,150000.0,2026-05-31,Wasserman
4653,NaN,NaN,1163778,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,United States,2002-06-13,Centre-Forward,Attack,right,193.0,NaN,NaN,NaT,NaN

In [18]:
# CHECKING NULL VALUES 
df3.isnull().sum()

appearance_id                  0
game_id                        0
player_id                      0
date_x                         0
player_name_x                  0
competition_id_x               0
yellow_cards                   0
red_cards                      0
goals                          0
assists                        0
minutes_played                 0
game_event_id                  0
date_y                         0
minute                         0
type_x                         0
description                    0
player_in_id                   0
player_assist_id               0
game_lineups_id                0
type_y                         0
number                         0
player_name_y                  0
team_captain                   0
position_x                     0
competition_id_y               0
season                         0
round                          0
date                           0
home_club_goals                0
away_club_goals                0
home_club_position             0
away_club_position             0
home_club_manager_name         0
away_club_manager_name         0
stadium                        0
attendance                     0
referee                        0
home_club_name                 0
away_club_name                 0
aggregate                      0
competition_type               0
name                           0
last_season                    0
current_club_id                0
player_code                    0
country_of_birth               0
date_of_birth                  0
sub_position                   0
position_y                     0
foot                           0
height_in_cm                   0
market_value_in_eur            0
highest_market_value_in_eur    0
contract_expiration_date       0
agent_name                     0
dtype: int64

In [15]:
df3.dtypes

appearance_id                          object
game_id                               float64
player_id                               int64
date_x                         datetime64[ns]
player_name_x                          object
competition_id_x                       object
yellow_cards                          float64
red_cards                             float64
goals                                 float64
assists                               float64
minutes_played                        float64
game_event_id                          object
date_y                         datetime64[ns]
minute                                float64
type_x                                 object
description                            object
player_in_id                          float64
player_assist_id                      float64
game_lineups_id                        object
type_y                                 object
number                                float64
player_name_y                          object
team_captain                          float64
position_x                             object
competition_id_y                       object
season                                float64
round                                  object
date                           datetime64[ns]
home_club_goals                       float64
away_club_goals                       float64
home_club_position                    float64
away_club_position                    float64
home_club_manager_name                 object
away_club_manager_name                 object
stadium                                object
attendance                            float64
referee                                object
home_club_formation                   float64
away_club_formation                   float64
home_club_name                         object
away_club_name                         object
aggregate                              object
competition_type                       object
name                                   object
last_season                             int64
current_club_id                         int64
player_code                            object
country_of_birth                       object
date_of_birth                  datetime64[ns]
sub_position                           object
position_y                             object
foot                                   object
height_in_cm                          float64
market_value_in_eur                   float64
highest_market_value_in_eur           float64
contract_expiration_date       datetime64[ns]
agent_name                             object
dtype: object

In [16]:
# THE home_club_formation,away_club_formation HAS NO VALUES SO DROPPING THESE COLUMNS FROM DATA SET
df3.drop(columns=['home_club_formation','away_club_formation'],inplace=True)

In [17]:
#SEGAREGATE THE OLUMNS INTO THE NUMERICAL  AND CATEGORICAL COLUMNS
import pandas as pd
import numpy as np

# segaregating the Numerical Columns from original data set
numerical_cols = df3.select_dtypes(include=['float64', 'int64']).columns
for col in numerical_cols:
    if df3[col].isnull().sum() > 0:
        df3[col].fillna(df3[col].median(), inplace=True)

# segaregating the Categorical Columns from original data set
categorical_cols = df3.select_dtypes(include=['object', 'category']).columns
for col in categorical_cols:
    if df3[col].isnull().sum() > 0:
        df3[col].fillna(df3[col].mode()[0], inplace=True)

# segaregating the Datetime Columns from original data set
datetime_cols = df3.select_dtypes(include=['datetime64[ns]']).columns
for col in datetime_cols:
    if df3[col].isnull().sum() > 0:
        # Replace with the median date
        df3[col].fillna(df3[col].median(), inplace=True)

C:\Users\marur\AppData\Local\Temp\ipykernel_2652\23230040.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(df3[col].median(), inplace=True)
C:\Users\marur\AppData\Local\Temp\ipykernel_2652\23230040.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(df3[col].mode()[0], inplace=True)
C:\Users\marur\AppData\Local\Temp\ipykernel_2652\23230040.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(df3[col].median(), inplace=True)
C:\Users\marur\AppData\Local\Temp\ipykernel_2652\23230040.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(df3[col].median(), inplace=True)
C:\Users\marur\AppData\Local\Temp\ipykernel_2652\23230040.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(df3[col].median(), inplace=True)
C:\Users\marur\AppData\Local\Temp\ipykernel_2652\23230040.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3[col].fillna(df3[col].median(), inplace=True)

In [20]:
#CHECKING IF ANY DUPLICATES ARE THERE
df4=df3.duplicated()
df4

0       False
1       False
2       False
3       False
4       False
        ...
4649    False
4650    False
4651    False
4652    False
4653    False
Length: 4654, dtype: bool

In [21]:
#DROPPING THE DUPLIACTES FROM THE DATA
df5=df3.drop_duplicates()
df5

,appearance_id,game_id,player_id,date_x,player_name_x,competition_id_x,yellow_cards,red_cards,goals,assists,...,country_of_birth,date_of_birth,sub_position,position_y,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,2222536_1321,2222536.0,1321,2012-08-26 00:00:00,Jermaine Jones,L1,1.0,0.0,0.0,1.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,1000000.0,8000000.0,2024-12-31,Wasserman
1,2231391_1321,2231391.0,1321,2012-09-01 00:00:00,Jermaine Jones,L1,0.0,0.0,1.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,1000000.0,8000000.0,2024-12-31,Wasserman
2,2231391_1321,2231391.0,1321,2012-09-01 00:00:00,Jermaine Jones,L1,0.0,0.0,1.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,1000000.0,8000000.0,2024-12-31,Wasserman
3,2231397_1321,2231397.0,1321,2012-09-28 00:00:00,Jermaine Jones,L1,1.0,0.0,0.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,1000000.0,8000000.0,2024-12-31,Wasserman
4,2231397_1321,2231397.0,1321,2012-09-28 00:00:00,Jermaine Jones,L1,1.0,0.0,0.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,1000000.0,8000000.0,2024-12-31,Wasserman
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4649,2224542_119169,2757218.0,795738,2016-07-20 12:00:00,Fabian Johnson,L1,0.0,0.0,0.0,0.0,...,United States,2003-08-26,Attacking Midfield,Midfield,right,175.0,4500000.0,4500000.0,2027-06-30,Wasserman
4650,2224542_119169,2757218.0,796429,2016-07-20 12:00:00,Fabian Johnson,L1,0.0,0.0,0.0,0.0,...,United States,2003-11-18,Right-Back,Defender,right,185.0,1500000.0,3000000.0,2025-12-31,CAA Stellar
4651,2224542_119169,2757218.0,860812,2016-07-20 12:00:00,Fabian Johnson,L1,0.0,0.0,0.0,0.0,...,United States,2002-04-22,Left Winger,Attack,right,182.0,350000.0,350000.0,2026-06-30,FGM
4652,2224542_119169,2757218.0,971613,2016-07-20 12:00:00,Fabian Johnson,L1,0.0,0.0,0.0,0.0,...,United States,2000-06-21,Defensive Midfield,Midfield,right,193.0,150000.0,150000.0,2026-05-31,Wasserman
4653,2224542_119169,2757218.0,1163778,2016-07-20 12:00:00,Fabian Johnson,L1,0.0,0.0,0.0,0.0,...,United States,2002-06-13,Centre-Forward,Attack,right,193.0,1000000.0,5000000.0,2024-12-31,Wasserman

In [22]:
#THE EXCEL FILE IS CONVERTED INTO CSV FILE AND NAMENG  AS FOOTBALL_DATA_MERGED_CLEANED.
df5.to_csv('Football_Data_Merged_Cleaned.csv', index=False)

print("File saved as 'Football_Data_Merged_Cleaned.csv'")

File saved as 'Football_Data_Merged_Cleaned.csv'

In [129]:
df5

,appearance_id,game_id,player_id,date_x,player_name_x,competition_id_x,yellow_cards,red_cards,goals,assists,...,country_of_birth,date_of_birth,sub_position,position_y,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,2222536_1321,2222536.0,1321,2012-08-26 00:00:00,Jermaine Jones,L1,1.0,0.0,0.0,1.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,1000000.0,8000000.0,2024-12-31,Wasserman
1,2231391_1321,2231391.0,1321,2012-09-01 00:00:00,Jermaine Jones,L1,0.0,0.0,1.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,1000000.0,8000000.0,2024-12-31,Wasserman
2,2231391_1321,2231391.0,1321,2012-09-01 00:00:00,Jermaine Jones,L1,0.0,0.0,1.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,1000000.0,8000000.0,2024-12-31,Wasserman
3,2231397_1321,2231397.0,1321,2012-09-28 00:00:00,Jermaine Jones,L1,1.0,0.0,0.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,1000000.0,8000000.0,2024-12-31,Wasserman
4,2231397_1321,2231397.0,1321,2012-09-28 00:00:00,Jermaine Jones,L1,1.0,0.0,0.0,0.0,...,Germany,1981-11-03,Defensive Midfield,Midfield,both,184.0,1000000.0,8000000.0,2024-12-31,Wasserman
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4649,2224542_119169,2757218.0,795738,2016-07-20 12:00:00,Fabian Johnson,L1,0.0,0.0,0.0,0.0,...,United States,2003-08-26,Attacking Midfield,Midfield,right,175.0,4500000.0,4500000.0,2027-06-30,Wasserman
4650,2224542_119169,2757218.0,796429,2016-07-20 12:00:00,Fabian Johnson,L1,0.0,0.0,0.0,0.0,...,United States,2003-11-18,Right-Back,Defender,right,185.0,1500000.0,3000000.0,2025-12-31,CAA Stellar
4651,2224542_119169,2757218.0,860812,2016-07-20 12:00:00,Fabian Johnson,L1,0.0,0.0,0.0,0.0,...,United States,2002-04-22,Left Winger,Attack,right,182.0,350000.0,350000.0,2026-06-30,FGM
4652,2224542_119169,2757218.0,971613,2016-07-20 12:00:00,Fabian Johnson,L1,0.0,0.0,0.0,0.0,...,United States,2000-06-21,Defensive Midfield,Midfield,right,193.0,150000.0,150000.0,2026-05-31,Wasserman
4653,2224542_119169,2757218.0,1163778,2016-07-20 12:00:00,Fabian Johnson,L1,0.0,0.0,0.0,0.0,...,United States,2002-06-13,Centre-Forward,Attack,right,193.0,1000000.0,5000000.0,2024-12-31,Wasserman